version: "3.1"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=ghjnbdjcnjzybt555
      - N8N_HOST=n8n.xminer.ru
      - N8N_PORT=5678
      - WEBHOOK_TUNNEL_URL=https://n8n.xminer.ru:5678
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=https://n8n.xminer.ru:5678
    volumes:
      - ~/.n8n:/home/node/.n8n
