services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "80:80"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=ghjwdtnfybt777
      - N8N_HOST=n8n.xminer.ru
      - N8N_PORT=80
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://n8n.xminer.ru
      - WEBHOOK_TUNNEL_URL=http://n8n.xminer.ru
      - N8N_SECURE_COOKIE=false
    volumes:
      - ~/.n8n:/home/node/.n8n
